export const CodeTypeMap = {
  static: 'static',
  angular: 'angular',
  react: 'react',
  'react-ts': 'react-ts',
  solid: 'solid',
  svelte: 'svelte',
  'test-ts': 'test-ts',
  'vanilla-ts': 'vanilla-ts',
  vanilla: 'vanilla',
  vue: 'vue',
  'vue-ts': 'vue-ts',
  node: 'node',
  nextjs: 'nextjs',
  vite: 'vite',
  'vite-react': 'vite-react',
  'vite-react-ts': 'vite-react-ts',
  'vite-preact': 'vite-preact',
  'vite-preact-ts': 'vite-preact-ts',
  'vite-vue': 'vite-vue',
  'vite-vue-ts': 'vite-vue-ts',
  'vite-svelte': 'vite-svelte',
  'vite-svelte-ts': 'vite-svelte-ts',
  astro: 'astro',
};
